## Matrix Algebra

### Exercises

**Exercise 1:** Calculate $-2E$, $G+F$, $4F-G$, $HG$, and $GE$ using the following matrix definitions.  Do the exercise on paper first, then check by doing the calculation with NumPy arrays.

$$
\begin{equation}
E = \left[ \begin{array}{r} 5 \\ -2 \end{array}\right] \hspace{1cm} 
F = \left[ \begin{array}{rr} 1 & 6 \\ 2 & 0 \\ -1 & -1 \end{array}\right] \hspace{1cm}
G = \left[ \begin{array}{rr} 2 & 0\\ -1 & 3 \\ -1 & 6 \end{array}\right] \hspace{1cm}
H = \left[ \begin{array}{rrr} 3 & 0 & 1 \\ 1 & -2 & 2 \\ 3 & 4 & -1\end{array}\right]
\end{equation}
$$

In [13]:
## Code solution here.
import numpy as np
E=np.array([[5],[-2]])
G=np.array([[2,0],[-1,3],[-1,6]])
F=np.array([[1,6],[2,0],[-1,-1]])
H=np.array([[3,0,1],[1,-2,2],[3,4,-1]])
print("-2E=",-2*E,"\n")
print("G+F=",G+F,"\n")
print("4F-G=",4*F-G,"\n")
print("HG=",H@G, "\n")
print("GE=",G@E, "\n")

-2E= [[-10]
 [  4]] 

G+F= [[ 3  6]
 [ 1  3]
 [-2  5]] 

4F-G= [[  2  24]
 [  9  -3]
 [ -3 -10]] 

HG= [[5 6]
 [2 6]
 [3 6]] 

GE= [[ 10]
 [-11]
 [-17]] 



**Exercise 2:** Find the values of $y$ so that this equation holds.

$$
\begin{equation}
\left[ \begin{array}{rr} 1 & 0 & 2 & -1 \\ 3 & 1 & -3 & 2 \\ 2 & 0 & 4 & 4 \\ 2 & 1 & -1 & -1 \end{array}\right]
\left[ \begin{array}{rr} y1 \\ y2 \\ y3 \\ y4\end{array}\right]=
\left[ \begin{array}{rr} 0 \\ 0 \\ 1 \\ 0 \end{array}\right] 
\end{equation}
$$

In [32]:
## Code solution here.
A=np.array([[1,0,2,-1],[3,1,-3,2],[2,0,4,4],[2,1,-1,-1]])
B=np.array([[0],[0],[1],[0]])
A_inv =np.linalg.inv(A) 
y=A_inv@B
# print(A_inv,"\n")
print("y=",y)

y= [[-0.16666667]
 [ 0.66666667]
 [ 0.16666667]
 [ 0.16666667]]


**Exercise 3:** Define NumPy arrays for the matrices $H$ and $G$ given below.  

$$
\begin{equation}
H = \left[ \begin{array}{rrr} 3 & 3 & -1  \\ -3 & 0 & 8 \\  1 & 6 & 5 \end{array}\right]\hspace{2cm}
G = \left[ \begin{array}{rrrr} 1 & 5 & 2 & -3 \\ 7 & -2 & -3 & 0 \\ 2 & 2 & 4 & 6\end{array}\right]
\end{equation}
$$

$(a)$ Multiply the second and third column of $H$ with the first and second row of $G$.  Use slicing to make subarrays.  Does the result have any relationship to the full product $HG$?

$(b)$ Multiply the first and second row of $H$ with the second and third column of $G$.  Does this result have any relationship to the full product $HG$?


In [52]:
## Code solution here.
H=np.array([[3,3,-1],[-3,0,8],[1,6,5]])
G=np.array([[1,5,2,-3],[7,-2,-3,0],[2,2,4,6]])
H_2c=H[:,1:]
G_2r=G[:2,:]
H_2r=H[:2,:]
G_2c=G[:,1:3]
result_a= H_2c@G_2r
result_b= H_2r@G_2c
# print(H_2r)
# print(G_2c)
print("The result of multiplying the two arrays: \n ",H@G)

print("\nThe result of multiplying the first two subarrays: \n ", result_a)
print("(a): No the result doesn't have any relationship to the full product \n")
print("The result of multiplying the second two subarrays: \n ", result_b)
print("(b): Yes the result has a relationship to the full product, It's a subarray of the product \n")



The result of multiplying the two arrays: 
  [[ 22   7  -7 -15]
 [ 13   1  26  57]
 [ 53   3   4  27]]

The result of multiplying the first two subarrays: 
  [[ -4  17   9  -9]
 [ 56 -16 -24   0]
 [ 41  20  -3 -18]]
(a): No the result doesn't have any relationship to the full product 

The result of multiplying the second two subarrays: 
  [[ 7 -7]
 [ 1 26]]
(b): Yes the result has a relationship to the full product, It's a subarray of the product 



**Exercise 4:** Generate a $4\times 4$ matrix $B$ with random integer entries.  Compute matrices $P = \frac12(B+B^T)$ and $Q = \frac12(B-B^T)$.  Rerun your code several times to get different matrices.  What do you notice about $P$ and $Q$?  Explain why it must always be true.       

In [73]:
## Code solution here.
B=np.random.randint(-10,10,size=(4,4))
B_T=B.transpose()
P=0.5*(B+B_T)
Q=0.5*(B-B_T)
print("Matrix P is:\n",P)
print("P is a symmetric matrix")
print("\nMatrix Q is:\n",Q)
print("Q is a skew-symmetric matrix")
#Matrix P is a symmetric matrix
#Matrix Q is a skew-symmetric matrix


Matrix P is:
 [[-8.   2.5 -3.   0. ]
 [ 2.5  0.  -1.5 -5.5]
 [-3.  -1.5  6.   4. ]
 [ 0.  -5.5  4.  -3. ]]
P is a symmetric matrix

Matrix Q is:
 [[ 0.   5.5 -6.   7. ]
 [-5.5  0.  -5.5 -1.5]
 [ 6.   5.5  0.   0. ]
 [-7.   1.5  0.   0. ]]
Q is a skew-symmetric matrix


**Exercise 5:** Create a Python function named **Angle** which takes two vectors as arguments and returns **cos(Theta)** where **Theta** is the angle between the two vectors. Use this function to show that vectors $U$ and $W$ are orthogonal.
    
$$
\begin{equation}
U = \left[ \begin{array}{rrr} 1 \\ -1 \\ 2 \end{array}\right]\hspace{2cm}
W = \left[ \begin{array}{rrrr} 2 \\ 0 \\ -1 \end{array}\right]
\end{equation}
$$




In [83]:
from numpy.linalg import norm
import math
## Code solution here.
def Angle(v1,v2):
  p=np.dot(v1,v2)
  norm_mult=norm(v1)*norm(v2)
  cosine_Theta=p/norm_mult
  Theta_rad= math.acos(cosine_Theta)
  Theta= Theta_rad*180/math.pi
  return Theta
u=[1,-1,2]
w=[2,0,-1]
Angle(u,w)  

90.0